
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - redis-server

  redis-server:
    image: "redis"
    restart: unless-stopped