name: Build and Deploy

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./backend2
        run: npm install

      - name: Create .env file
        working-directory: ./backend2
        run: |
          
          touch .env
          
          echo "mongodb+srv://Anmol_tranquil:tnPBlD8fEkT58ue4@cluster0.r48nqqn.mongodb.net/?retryWrites=true&w=majority" >> .env
          echo "TOKEN_KEY=anmolpandey" >> .env
          echo "CLOUDNAME=dkmf3e7c7" >> .env
          echo "APIKEY=383915659521579" >> .env
          echo "JWT_SECRET=hisecretname" >> .env
          echo "CLOUD_SECRET=mAF-fvw3RugyzzRok9BL7OeAazQ" >> .env
          
          # echo "MONGO_DB_TEST=mongodb+srv://parthirache8:ufPeWVX7HabgpyVh@cluster0.eo9svyz.mongodb.net/test" >> .env

      - name: Run test
        working-directory: ./backend2
        run: |
          npm test
          if [ $? -ne 0 ]; then
            echo "Tests failed, exiting."
            exit 1
          fi

      - name: Build Docker Image for Server
        working-directory: ./backend2
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tranquilbackend .

      - name: Build Docker Image for Frontend
        working-directory: ./frontend2
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tranquilfrontend .        

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to DockerHub
        working-directory: ./backend2
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/tranquilbackend

      - name: Push Image to DockerHub
        working-directory: ./frontend2
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/tranquilfrontend